services:
  - name: backend
    type: web
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg libavcodec-dev libavformat-dev libavdevice-dev libavutil-dev libavfilter-dev libswscale-dev libswresample-dev
      pip install -r requirements.txt
    startCommand: python backend-main.py
